[package]
name = "fexpr"
version = "0.1.0"
edition = "2024"
authors = ["karl robeck alferez <karlalferezfx@gmail.com>"]
license = "MIT"
license-file = "LICENSE.md"

[dependencies]
anyhow = "1.0.98"
thiserror = "2.0.12"

[dev-dependencies]
rstest = "0.25.0"
